spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        format_sql: true
        show_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test;MODE=MySQL;
    username: sa
    password:

app:
  jwt:
    secret: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb

